<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LNTLP0127" ignored="1" tests="1" failures="1" timestamp="09 Jul 2018 13:11:45 GMT" time="0.029" errors="0">
  <testcase name="rollscoreof4" time="0.005" classname="GameTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [4]
	at GameTest.rollscoreof4(GameTest.java:23)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- rollscoreof4 -->
  <testcase name="test" time="0.0" classname="GameTest">
    <ignored/>
  </testcase> <!-- test -->
</testsuite>
